# Generated by Django 3.0.8 on 2020-08-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_service_body_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='body',
            field=models.TextField(default='Body'),
        ),
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.TextField(default='Ссылка на видео'),
        ),
    ]
